application: 
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "local_host"
  sender_email: "test@gmail.com"
  authorization_toke: "secret_token"
